// Mocks generated by Mockito 5.4.6 from annotations
// in masstodo/test/providers/task_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i4;
import 'package:masstodo/database/database_helper.dart' as _i2;
import 'package:masstodo/models/task_model.dart' as _i3;
import 'package:masstodo/repositories/task_repository.dart' as _i5;
import 'package:masstodo/utils/notification_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskItem_1 extends _i1.SmartFake implements _i3.TaskItem {
  _FakeTaskItem_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlutterLocalNotificationsPlugin_2 extends _i1.SmartFake
    implements _i4.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i5.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  _i6.Future<_i3.TaskItem> createTask(_i3.TaskItem? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i6.Future<_i3.TaskItem>.value(
              _FakeTaskItem_1(this, Invocation.method(#createTask, [task])),
            ),
          )
          as _i6.Future<_i3.TaskItem>);

  @override
  _i6.Future<List<_i3.TaskItem>> getAllTasks({
    bool? includeCompleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTasks, [], {
              #includeCompleted: includeCompleted,
            }),
            returnValue: _i6.Future<List<_i3.TaskItem>>.value(<_i3.TaskItem>[]),
          )
          as _i6.Future<List<_i3.TaskItem>>);

  @override
  _i6.Future<_i3.TaskItem?> getTaskById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [id]),
            returnValue: _i6.Future<_i3.TaskItem?>.value(),
          )
          as _i6.Future<_i3.TaskItem?>);

  @override
  _i6.Future<int> updateTask(_i3.TaskItem? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> updateTaskCompletion(String? id, bool? isCompleted) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskCompletion, [id, isCompleted]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> deleteTasksByCategoryId(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTasksByCategoryId, [categoryId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<Map<String, dynamic>> getDashboardStats() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardStats, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i7.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FlutterLocalNotificationsPlugin get flutterLocalNotificationsPlugin =>
      (super.noSuchMethod(
            Invocation.getter(#flutterLocalNotificationsPlugin),
            returnValue: _FakeFlutterLocalNotificationsPlugin_2(
              this,
              Invocation.getter(#flutterLocalNotificationsPlugin),
            ),
          )
          as _i4.FlutterLocalNotificationsPlugin);

  @override
  set flutterLocalNotificationsPlugin(
    _i4.FlutterLocalNotificationsPlugin? value,
  ) => super.noSuchMethod(
    Invocation.setter(#flutterLocalNotificationsPlugin, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> scheduleTaskNotification(_i3.TaskItem? task) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleTaskNotification, [task]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelTaskNotification(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelTaskNotification, [taskId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
